version: '3.8'

services:
  app:
    build: .
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
  postgres:
    image: postgres:15
    container_name: weather-postgres
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 