version: '3.8'

services:
  app:
    build: .
    ports:
      - "8070:8070"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=weatherdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - weather-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    container_name: weather-postgres
    environment:
      - POSTGRES_DB=weatherdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - weather-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  weather-network:
    driver: bridge

volumes:
  postgres-data: